dashboard features
ctc-uci/oc-habitats-backend pull request #37
Opened 2022-03-31 22:40 UTC by ctc-devops

[Figma](https://www.figma.com/file/lf9VVjL1h6YAhqdQXEEr96/%5BDesigner%5D-Wireframes?node-id=1852%3A59390)

- [ ] Get recently approved monitor logs, if any
- [ ] Get monitor log segments owned by current user
- [ ] See which of current user's segments have/haven't had submitted logs this month
- [ ] Get edits that were requested by admin on current user's submitted logs
- [ ] Get monitor log drafts ?
closes #31

2022-04-04 20:40 UTC, ctc-devops commented on routes/volunteer.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-05 05:50 UTC, ctc-devops commented on routes/volunteer.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-06 19:30 UTC, ctc-devops commented on routes/dashboard.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-06 19:30 UTC, ctc-devops commented on routes/dashboard.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-06 19:30 UTC, ctc-devops commented on routes/dashboard.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-10 22:48 UTC, ctc-devops commented on routes/assignments.service.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-10 22:48 UTC, ctc-devops commented on routes/assignments.service.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-14 21:33 UTC, ctian1 requested changes

2022-04-14 21:33 UTC, ctian1 commented on models/submission.schema.js
> +    enum: ['unsubmitted', 'underReview', 'approved', 'editsRequested'],
should prob be UNDER_REVIEW, etc.

2022-04-14 21:43 UTC, ctian1 approved these changes

2022-04-14 21:45 UTC, merged