Upload profile pic to mongo updates
ctc-uci/oc-habitats-backend pull request #49
Opened 2022-04-14 03:12 UTC by PhillipChn

2022-04-14 03:31 UTC, ctc-devops commented on app.js
>  require('dotenv').config();
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Delete `⏎`
```suggestion
require('dotenv').config();
```

2022-04-14 03:31 UTC, ctc-devops commented on app.js
>  app.use(cookieParser());
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Delete `⏎`
```suggestion
app.use(cookieParser());
```

2022-04-14 03:31 UTC, ctc-devops commented on app.js
> +app.use('/users', usersRouter);
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'usersRouter' is not defined.

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +const userSchema = new mongoose.Schema({
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `⏎··`
```suggestion
const userSchema = new mongoose.Schema(
  {
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  firebaseId: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    firebaseId: String,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  firstName: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    firstName: String,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  lastName: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    lastName: String,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  email: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    email: String,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  password: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    password: String,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  role: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    role: String,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  isActive: { type: Boolean, default: true },
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    isActive: { type: Boolean, default: true },
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  isTrainee: { type: Boolean, default: false },
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    isTrainee: { type: Boolean, default: false },
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  registered: Boolean,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    registered: Boolean,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  profileImage: {
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    profileImage: {
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +    data: Buffer,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
      data: Buffer,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +    contentType: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `····` with `······`
```suggestion
      contentType: String,
```

2022-04-14 03:31 UTC, ctc-devops commented on models/user.schema.js
> +  },
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    },
```

2022-04-14 03:31 UTC, ctc-devops commented on routes/user.router.js
>  // create profile in DB
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Delete `⏎`
```suggestion
// create profile in DB
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  firebaseId: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    firebaseId: String,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  firstName: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    firstName: String,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  lastName: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    lastName: String,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  email: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    email: String,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  password: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    password: String,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  isActive: { type: Boolean, default: true },
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    isActive: { type: Boolean, default: true },
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  registered: Boolean,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    registered: Boolean,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  profileImage: {
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
    profileImage: {
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +    contentType: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
      contentType: String,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +    data: Buffer,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `··`
```suggestion
  pr  ofileImage: {
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +    contentType: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `····` with `······`
```suggestion
      data: Buffer,
```

2022-04-14 03:32 UTC, ctc-devops commented on models/user.schema.js
> +  isTrainee: { type: Boolean, default: false },
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    isTrainee: { type: Boolean, default: false },
```

2022-04-14 03:33 UTC, ctc-devops commented on models/user.schema.js
> +  role: String,
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `··` with `····`
```suggestion
    role: String,
```

2022-04-14 21:05 UTC, janehvo requested changes

2022-04-14 21:05 UTC, janehvo commented on models/user.schema.js
> +    password: String,
We're not storing passwords in mongo, only firebase

2022-04-21 04:44 UTC, janehvo approved these changes

2022-04-21 04:44 UTC, merged