backend for emergency numbers page
ctc-uci/oc-habitats-backend pull request #58
Opened 2022-04-28 06:32 UTC by aahsue

2022-04-28 21:05 UTC, janehvo requested changes
good work Andrea :D also please resolve merge conflicts

2022-04-28 21:05 UTC, janehvo commented on routes/numbers.router.js
> +router.put('/update/:id', async (req, res) => {
You can remove `/update` from this route and leave it as just `/:id`

2022-04-28 21:05 UTC, janehvo commented on services/numbers.service.js
> +    throw new Error('Arguments missing in species');
Can you fix this error message so that it relates to numbers?

2022-04-28 21:05 UTC, janehvo commented on services/numbers.service.js
> +};
Can you also handle the error if they try adding a number that already exists?

2022-04-28 21:05 UTC, janehvo commented on services/numbers.service.js
> +};
Can you handle an error where the updateNumber already exists?

2022-05-05 07:37 UTC, ctc-devops commented on routes/numbers.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-05 07:37 UTC, ctc-devops commented on routes/numbers.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-05 07:37 UTC, ctc-devops commented on routes/numbers.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-05 07:37 UTC, ctc-devops commented on routes/numbers.router.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-05 07:37 UTC, ctc-devops commented on services/numbers.service.js
> +  NumbersModel.findOne({ name: number.name }, function (err) {
⚠️ **[eslint]** <[func-names](https://eslint.org/docs/rules/func-names)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected unnamed function.

2022-05-05 07:37 UTC, ctc-devops commented on services/numbers.service.js
> +  NumbersModel.findOne({ number: number.number }, function (err) {
⚠️ **[eslint]** <[func-names](https://eslint.org/docs/rules/func-names)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected unnamed function.

2022-05-05 07:37 UTC, ctc-devops commented on services/numbers.service.js
> +  NumbersModel.findOne({ name: updatedNumber.name }, function (err) {
⚠️ **[eslint]** <[func-names](https://eslint.org/docs/rules/func-names)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected unnamed function.

2022-05-05 07:37 UTC, ctc-devops commented on services/numbers.service.js
> +  NumbersModel.findOne({ number: updatedNumber.number }, function (err) {
⚠️ **[eslint]** <[func-names](https://eslint.org/docs/rules/func-names)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected unnamed function.

2022-05-05 07:39 UTC, janehvo approved these changes

2022-05-05 07:40 UTC, merged